required: sudo
services:
        - docker
before_install:
        - docker build -t aliavci/docker-react -f Dockerfile.dev .
script:
        - docker run aliavci/docker-react npm run test -- --coverage
